[package]
name = "stroke-confusion-example"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lyon = "0.17.10"
wgpu = "0.11.0"
futures = "0.3.5"
bytemuck = "1.2.0"
png = "0.16"
